name = "gluri"
version = "2.0.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
 description = "Uri (RFC 3986) library for Gleam"
 licences = ["Apache-2.0"]
 repository = { type = "github", user = "pendletong", repo = "uri" }
 links = [{ title = "RFC 3986", href = "https://www.ietf.org/rfc/rfc3986.txt" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.
#

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
splitter = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
startest = ">= 0.7.0 and < 1.0.0"
glychee = ">= 1.1.2 and < 2.0.0"
